websiteSofie/urls.py
## Imports
# Nodig om urls te laten werken
from django.conf import settings
from django.conf.urls import include, url , handler404 , handler500 , patterns
from django.conf.urls.static import static
# Django-Admin gerelateerde urls
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import password_reset
# Importeren van alle views
from . import views
# Vertalingsconventie
from django.conf.urls.i18n import i18n_patterns

## Url patterns
urlpatterns = [
    #admin url
    url(r'^admin/', admin.site.urls),
    #vertalingsconventie
    url(r'^i18n/', include('django.conf.urls.i18n')),
    #homepagina
    url(r'^$', views.home, name='home'),
    #contactpagina
    url(r'^contact/', views.contact, name='contact'),
    #pandenpagina die te koop zijn
    url(r'^kopen/', views.kopen, name='kopen'),
    #pandenpagina die te huur zijn
    url(r'^huren/', views.huren, name='huren'),
    #disclaimer footer
    url(r'^disclaimer/', views.disclaimer, name='disclaimer'),
    #privacybeleid footer
    url(r'^privacybeleid/', views.privacybeleid, name='privacybeleid'),
    #loginpagina
    url(r'^login/', views.LoginUser, name='login'),
    #more pagina incl. partners, referenties, ebook, nieuwsbrief,advies
    url(r'^more/', views.more, name='more'),
    #loginpagina mobile
    url(r'^loginpage/', views.loginpage, name='loginpage'),
    #logout
    url(r'^logout/', views.logout_user, name='logout'),
    #pand detail
    url(r'^pand/(?P<pand_id>[0-9]+)',views.pand, name='pand'),
    #zoekfilter
    url(r'^search/$', views.search, name='search_estate'),
    #paswoord is verstuurd
    url(r'^resetpassword/passwordsent/$', auth_views.password_reset_done, {'template_name': 'websiteSofie/password_reset_done.html'}, name='password_reset_done'),
    #reset paswoord pagina
    url(r'^resetpassword/$', auth_views.password_reset, {'template_name': 'websiteSofie/password_reset_form.html'}, name='password_reset'),
    #unieke url voor paswoord te reseten
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm,{'template_name': 'websiteSofie/password_reset_confirm.html'}, name='password_reset_confirm'),
    #paswoord reset voltooid
    url(r'^reset/done/$', auth_views.password_reset_complete, {'template_name': 'websiteSofie/password_reset_complete.html'}, name='password_reset_complete'),
    #verkoperspagina
    url(r'^userPage/', views.userPage, name='userPage'),
    #detail zoekfilter
    url(r'^detail_search/$',views.detail_search, name='detail_search_estate'),
    #nieuwsbrief inschrijven
    url(r'^subscribe/', views.subscribe, name='subscribe'),
    #nieuwsbrief uitschrijven
    url(r'^unsubscribe/', views.unsubscribe, name='unsubscribe'),
    #accountgegevens updaten
    url(r'^update_account/', views.update_account, name='update account'),
    #media url
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,}),
]

# Error handlers
handler404 = views.error_404
handler500 = views.error_500

websiteSofie/models.py
# imports voor werkende models
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from uuid import uuid4
from websiteSofie.storage import OverwriteStorage
from django.db.models import signals
from django.conf import settings

#mail functie importeren
from django.core.mail import send_mail

# vertalingsconventie
from django.utils.translation import ugettext_lazy as _

# ophalen server tijd
def get_current_date():
    return timezone.now

#account model waarbij de gegevens van een verkoper worden opgeslagen
class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user', verbose_name="Gebruiker")
    city = models.CharField(max_length = 50, blank=True, verbose_name="Stad")
    street = models.CharField(max_length = 50, blank=True, verbose_name="Straat")
    house_number = models.CharField(max_length = 50, blank=True, verbose_name="Huisnummer")
    area_code = models.CharField(max_length = 50, blank=True, verbose_name="Postcode")
    birth_date = models.DateField(null = True, blank=True, verbose_name="Geboortedatum")
    mobile_number = models.CharField(max_length = 15, null = True, blank=True, verbose_name="GSM nummer")
    telephone_number = models.CharField(max_length = 15, null = True, blank=True, verbose_name="Telefoonnummer")

    def __unicode__(self):
        return u'%s %s' % (self.user.first_name, self.user.last_name)

    # maakt een Account model aan gelinkt met
    def create_user_account(sender, instance, created, **kwargs):
        if created:
            profile, created = Account.objects.get_or_create(user=instance)

    post_save.connect(create_user_account, sender=User)

User.profile = property(lambda u: Account.objects.get_or_create(user=u)[0])

#Estate model voor het aanmaken van een nieuw pand
class Estate(models.Model):
    #verschillende mogelijkheden voor het pand
    ISAVALAIBLE_CHOICES = (
        ('AVAILABLE', 'Beschikbaar voor site'),
        ('N_AVAILABLE', 'Niet beschikbaar voor site'),
        ('IS_VERKOCHT', 'Is verkocht'),
        ('IS_REFERENTIE', 'Is verkocht en referentie'),
    )
    #provincies van belgie
    PROVINCE_CHOICES=(
        ('ANTWERPEN', 'Antwerpen'),
        ('OOST_VLAANDEREN', 'Oost-Vlaanderen'),
        ('WEST_VLAANDEREN', 'West-Vlaanderen'),
        ('LIMBURG', 'Limburg'),
        ('LUIK', 'Luik'),
        ('NAMEN', 'Namen'),
        ('VLAAMS_BRABANT', 'Vlaams-brabant'),
        ('WAALS_BRABANT', 'Waals-Brabant'),
        ('HENEGOUWEN', 'Henegouwen'),
        ('BRUSSEL', 'Brussel'),
        ('LUXEMBURG', 'Luxemburg'),
    )
    #typen bebouwing
    BEBOUWING_KEUZES=(
        (_('OPEN'), _('Open')),
        (_('HALFOPEN'),_('Halfopen')),
        (_('GESLOTEN'),_('Gesloten')),
    )
    #pand types
    ESTATE_TYPES=(
        (_('HUIS'),_('Huis')),
        (_('APPARTEMENT'),_('Appartement')),
        (_('GROND'),_('Grond')),
        (_('KAMER/KOT'),_('Kamer/Kot')),
        (_('ANDERE'),_('Andere')),
    )

    # pand gegevens
    adres = models.CharField(max_length = 20, verbose_name="Adres")
    house_number = models.IntegerField(default = '1', verbose_name="Huisnummer")
    bus_nummer = models.CharField(max_length = 20, blank=True)
    area_code = models.CharField(max_length = 8, verbose_name="Postcode")
    town = models.CharField(max_length = 50, verbose_name="Gemeente")
    provincie = models.CharField(max_length=30,choices=PROVINCE_CHOICES, default='ANTWERPEN', verbose_name="Provincie")
    country = models.CharField(max_length=50,default='Belgie', verbose_name="Land")

    hits = models.IntegerField(default='0', verbose_name="Hits")
    sale = models.BooleanField(verbose_name="Te koop")
    rent = models.BooleanField(verbose_name="Te huur")

    sale_price = models.DecimalField(max_digits = 19, decimal_places = 2, verbose_name="Verkoopprijs")
    rent_price = models.DecimalField(max_digits = 19, decimal_places = 2, verbose_name="Verhuurprijs")
    date_placed = models.DateField(default = get_current_date(), verbose_name="Datum geplaatst")
    beschikbaarheid = models.CharField(max_length=20,choices=ISAVALAIBLE_CHOICES, default='AVAILABLE', verbose_name="Beschikbaarheid")

    bedrooms = models.IntegerField(default='1', verbose_name="Slaapkamers")
    bathrooms = models.IntegerField(default='1', verbose_name="Badkamers")

    bebouwing = models.CharField(max_length=30,choices=BEBOUWING_KEUZES,blank=True, verbose_name="Bebouwing")
    type_estate = models.CharField(max_length=50,choices=ESTATE_TYPES,default='HUIS',blank=True, verbose_name="Type vastgoed")
    surface = models.CharField(max_length=50,default=" ", verbose_name="Oppervlakte")
    habitable_surface = models.CharField(max_length=50,default=" ", verbose_name="Bewoonbare oppervlakte")
    description = models.TextField(default="Geen beschrijving beschikbaar", verbose_name="Beschrijving")
    referencenumber = models.CharField(max_length=50,default=" ",unique=True, verbose_name="Referentienummer")

    indekijker = models.BooleanField(default=False, verbose_name="In de kijker")

    class Meta:
        verbose_name_plural = "Vastgoed"

    # returnt alle afbeeldingen van een pand
    def get_estateImages(self):
        estate_images=EstateImage.objects.filter(estate=self)
        return estate_images

    # returnt de Displayimage van een pand
    def get_estateDisplayImage(self):
        display_image=EstateImage.objects.filter(estate=self,is_display="1")
        return display_image

    # maakt een qr-code voor een pand aan en displayt deze op de admin estate-view pagina
    def qr_code(self):
        return '<img src="https://chart.googleapis.com/chart?chs=150x150&amp;cht=qr&amp;chl=http://www.viasofie.be/pand/%s">' % self.id
    qr_code.allow_tags = True

    # displayt de Hoofdafbeelding op de admin estate-view pagina
    def image_tag(self):
        photos = EstateImage.objects.filter(estate=self,is_display="1")
        for img in photos:
            return u'<img src="http://localhost:8000/media/%s"style="max-width:200px;" />' % img.image
    image_tag.short_description = "Foto"
    image_tag.allow_tags = True

    def __unicode__(self):
        return u'%s %s' % (self.adres, self.house_number)

#model voor het opslaan van afbeeldingen gelinkt aan een pand
class EstateImage(models.Model):
    estate = models.ForeignKey(Estate, related_name='images', verbose_name="Vastgoed")
    image = models.ImageField(upload_to = "images/", verbose_name = 'Afbeelding')
    is_display = models.BooleanField(default=False, verbose_name="Hoofdafbeelding")

#model om een status toe te voegen en aan te passen
class Status(models.Model):
    status_name = models.CharField(max_length = 50)
    date_placed = models.DateField(default=get_current_date())
    description=models.TextField(default="Geen beschrijving beschikbaar")

    class Meta:
        verbose_name_plural="Status"

    def __unicode__(self):
        return self.status_name

# stuurt een mail bij het wijzigen of aanmaken van een pand status
def update_status(sender,instance, **kw):
    pand = instance.estate_ID
    if pand.estate_sellers_set.all():
        for seller in pand.estate_sellers_set.all():
            if seller.user_ID.email:
                #mail sturen naar verkoper waar status van een pand is aangespast/toegevoegd
                user_email = seller.user_ID.email
                page_url = 'http://localhost:8000/userPage'
                subject = 'Jouw pand heeft een nieuwe status'
                mesagge = 'Een van jouw panden heeft een nieuwe status, bekijk deze op: %s' %(page_url)
                from_email = settings.EMAIL_HOST_USER
                send_mail(subject, mesagge, from_email, [user_email], fail_silently=False)
                print('mail sent to '+user_email)
            else:
                print('no email.')

#model om status toe te voegen/ aan te passen gelinkt met een pand
class Estate_Status(models.Model):
    estate_ID = models.ForeignKey(Estate, on_delete=models.CASCADE)
    status_ID = models.ForeignKey(Status, on_delete=models.CASCADE)
    date_placed = models.DateField(default=get_current_date())

    def __unicode__(self):
        return u'%s %s: %s' % (self.estate_ID.adres, self.estate_ID.house_number, self.status_ID.status_name)
    class Meta:
        verbose_name_plural = "Vastgoed status"

# signal die mail verstuurt bij het updaten van een Estate Status
signals.post_save.connect(update_status, sender=Estate_Status)

#model om criterias toe te voegen die een pand kunnen hebben
class Criteria(models.Model):
    name = models.CharField(max_length = 50, verbose_name="Naam")

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Criteria voor vastgoed"

#model om een criteria te linken met een pand
class Estate_Criteria(models.Model):
    estate_ID = models.ForeignKey(Estate, on_delete=models.CASCADE, verbose_name="Vastgoed_ID")
    criteria_ID = models.ForeignKey(Criteria, on_delete=models.CASCADE, verbose_name="Criteria_ID")
    value = models.CharField(max_length = 100, verbose_name="Waarde")

    def __unicode__(self):
        return u'%s => %s' % (self.criteria_ID.name, self.value)

    class Meta:
        verbose_name_plural = "Vastgoed criteria"

#model om een review op te slaan in de database, hierdoor kan de admin bepalen welke review er op haar site worden getoond
class Review(models.Model):
    review_text = models.TextField(verbose_name="Review tekst")
    review_title = models.CharField(max_length = 50, verbose_name="Review titel")
    review_rating = models.IntegerField(default = 0, verbose_name="Review beoordeling")
    date = models.DateField(default=get_current_date(), verbose_name="Datum")
    approved = models.BooleanField(default=False, verbose_name="Goedgekeurd")

websiteSofie/forms.py
##Imports

from django import forms
from django.forms import ModelForm
from websiteSofie.models import *
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
from nocaptcha_recaptcha.fields import NoReCaptchaField
from django.core.validators import MaxValueValidator, MinValueValidator

# Form voor ingave zoekfilter -> kopen.html | huren.html | results.html
class SearchForm(forms.Form):
    search = forms.CharField(label='search',
                    widget=forms.TextInput(attrs={'placeholder': 'Gemeente, referentienummer, adres...'}), max_length=50)

# Login pop up form voor grote schermen -> _navbar.html
# Login form voor mobile/kleine schermen -> loginpage.html
class LoginForm(forms.ModelForm):
    email = forms.EmailField(label = _('E-mailadres'))
    password = forms.EmailField(label = _('Wachtwoord'),widget=forms.PasswordInput())
    class Meta:
        model=User
        fields=['email','password']

# Form om te registreren voor de Ebook -> more.html
class Ebook(forms.ModelForm):
    name = forms.CharField(label='Naam', max_length=100)
    email = forms.EmailField(label='Email', max_length=100)
    captcha = NoReCaptchaField()
    class Meta:
        model=Ebook
        fields=['name','email']

# Form voor contactformulier -> contact.html
class ContactForm(forms.ModelForm):
    name=forms.CharField(label='Naam', max_length=100)
    email=forms.EmailField(label='E-mail', max_length=100)
    subject=forms.CharField(label='Onderwerp',max_length=100)
    text=forms.CharField(label='Tekst',widget=forms.Textarea)
    captcha = NoReCaptchaField(label="")
    class Meta:
        model=Contact
        fields=['name','email','subject','text']

# Form om een review te schrijven -> more.html
class ReviewForm(forms.ModelForm):
    review_title = forms.CharField(label='Review titel', max_length = 50)
    review_text = forms.CharField(label='Review tekst', widget=forms.Textarea)
    review_rating = forms.IntegerField(label='Review beoordeling',validators=[
            MaxValueValidator(5),
            MinValueValidator(0)
        ],
        widget=forms.TextInput(attrs={'placeholder': 'beoordeling van 0 tot 5'}),)

    class Meta:
        model=Review
        fields=['review_title','review_text','review_rating']

# Form om te registreren voor de nieuwsbrief -> more.html
class SubscriptionForm(forms.ModelForm):
    name=forms.CharField(label='Naam', max_length=80)
    email=forms.EmailField(label='Email', max_length=50)
    class Meta:
        model=Subscription
        fields=['name','email']

# UpdateForm voor Userprofielen -> userPage.html
class UserUpdateForm(forms.ModelForm):
    first_name = forms.CharField(label='Voornaam', max_length = 20)
    last_name = forms.CharField(label='Achternaam', max_length = 20)

    class Meta:
        model=User
        fields=['first_name','last_name']

# UpdateForm voor Accountgegevens -> userpage.html
class AccountUpdateForm(forms.ModelForm):
    city = forms.CharField(label='Stad', max_length=50)
    street = forms.CharField(label='Straat', max_length=50)
    house_number = forms.CharField(label='Huisnummer',max_length=10)
    area_code = forms.CharField(label='Postcode',max_length=50)
    birth_date = forms.DateField(label='Geboortedatum', widget=forms.TextInput(attrs={'placeholder': 'jjjj-mm-dd'}))
    mobile_number = forms.CharField(label='Gsm nummer', max_length=15)
    telephone_number = models.CharField(max_length=15)

    class Meta:
        model=Account
        fields=['city','street','house_number','area_code','birth_date','mobile_number','telephone_number']

websiteSofie/templates/websiteSofie/base.html
{% load staticfiles %}
<!--Dit is de html pagina die wordt overgeerfd door alle html paginas-->
<!DOCTYPE html>
<html>
<head>
{% include "partials/_head.html" %}
</head>
<body>
{% include "partials/_navbar.html" %}

<div class="page">
  <p class ="break"></p>
  <div class ="container">
{% block content %}

{% endblock %}
  </div>
  
</div>
{% include "partials/_footer.html" %}
</body>
</html>

websiteSofie/templates/websiteSofie/contact.html
<!--Contact pagina-->
{% extends 'websiteSofie/base.html' %}
{% load staticfiles %}
{% block content %}

<!--Google maps en contactinformatie-->
<h1>Contact</h1>
<div class="col-sm-8">
  <p class="break"></p>
  <iframe
    width=100%
    height="450"
    frameborder="0" style="border:0"
    src="https://www.google.com/maps/embed/v1/place?key=AIzaSyA3cAlVyl5joqj5sQhFoX_i_SOswbuapMo&zoom=14&center=51.172278,4.501100
      &q=Mussenhoevelaan+101,Boechout+Belgium" allowfullscreen>
  </iframe>
  <p class="break"></p>
</div>
<div class="col-sm-4">
  <h1>Via Sofie</h1>
  <p>Mussenhoevelaan 101</p>
  <p>2530 Boechout</p>
  <p>België</p>
  <p>+32483713710<p>
    <a href="mailto:emailadres:info@viasofie.be">info@viasofie.be</a><p class="break"></p>
    <img class="contactlogo" src="{% static "img/contact.png" %}"  alt="logo viasofie" width="110px" height="180px"/>
</div>
</div>
<p class="break"></p>
<!-- contactformulier -->
<div class ="container">
  <h1>Vragen? Contacteer mij</h1>
  <p>Hebt u vragen? Aarzel dan niet om mij te contacteren via dit formulier.</p>
  <p class="break"></p>
  <form action="" method="post">
    {% csrf_token %}

    <table align="center">
      {{ form }}
    </table>

    <input type="submit" value="Verstuur" />
  </form>
</div>
{% endblock %}

websiteSofie/templates/websiteSofie/contact_succes.html
<!--Contactformulier succes pagina-->
<head>
  <meta http-equiv="refresh" content="3;url=/contact" />
</head>
{% extends 'websiteSofie/base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
<h1>{% trans "Contactformulier" %}</h1>

<p>{% trans "Uw Contactformulier is succesvol doorgestuurd" %}</p>

{% endblock %}

websiteSofie/templates/websiteSofie/kopen.html
<head>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
</head>
{% extends 'websiteSofie/base.html' %}
{% load staticfiles %}
{% load i18n %}
{% load humanize %}
{% block content %}
<h1>{% trans "Huizen te koop" %}</h1>
<!--Zoekfilter-->
<form method="POST" action="{% url 'search_estate' %}">
  {% csrf_token %}
  {{ searchform }}
  <input type="hidden" name="status" value="kopen">
  <button type="submit" class="btn-searchfilter">{% trans "Zoeken" %}</button>
</form>
<!--Gedetailleerde zoekfilter-->
<button type="button" class="btn-searchfilter" data-toggle="collapse" data-target="#detailsearch">{% trans "Zoekfilters" %}</button>
<div id="detailsearch" class="collapse">
  <form id="search_engine" method="GET" action="{% url 'detail_search_estate' %}">
    {% csrf_token %}
    <table>
      <tr>
        <input type="hidden" name="status" value="kopen">
        <div class="col-md-6"/>
          <label class="searchlabel" for="id_adres">{% trans "Straatnaam" %}:</label><input id="id_adres" maxlength="30" name="adres" type="text" placeholder="Straatnaam" />
          <label class="searchlabel" for="id_area_code">{% trans "Postcode" %}:</label><input id="id_area_code" maxlength="8" name="area_code" type="text" placeholder="Postcode"/>
        </div>
        <div class="col-md-6"/>
          <label class="searchlabel" for="id_town">{% trans "Stad" %}:</label><input id="id_town" maxlength="30" name="town" type="text" placeholder="Stad"/>
          <label class="searchlabel" for="id_province">{% trans "Provincie" %}:</label><input id="id_province" maxlength="30" name="province" type="text" placeholder="Provincie"/>
        </div>
        <div class="col-md-6"/>
          <label class="searchlabel" for="id_bedrooms">{% trans "Slaapkamers" %}:</label><input id="id_bedrooms" maxlength="1" name="bedroomsmin" type="text" placeholder="min"/><input id="id_bedrooms" maxlength="1" name="bedroomsmax" type="text" placeholder="max"/>
          <label class="searchlabel" for="id_bathrooms">{% trans "Badkamers" %}:</label><input id="id_bathrooms" maxlength="1" name="bathroomsmin" type="text" placeholder="min"/></label><input id="id_bathrooms" maxlength="1" name="bathroomsmax" type="text" placeholder="max"/>
        </div>
        <div class="col-md-6"/>
          <label class="searchlabel" for="id_bebouwing">{% trans "Bebouwing" %}:</label>
            <select name="bebouwing">
              <option value="" selected="selected">------</option>
              <option value="OPEN">{% trans "Open" %}</option>
              <option value="HALFOPEN">{% trans "Halfopen" %}</option>
              <option value="GESLOTEN">{% trans "Gesloten" %}</option>
            </select>
          <label class="searchlabel" for="id_type">{% trans "Type" %}:</label>
            <select name="type">
              <option value="" selected="selected">------</option>
              <option value="HUIS">{% trans "Huis" %}</option>
              <option value="APPARTEMENT">{% trans "Appartement" %}</option>
              <option value="KAMER/KOT">{% trans "Kamer / Kot" %}</option>
              <option value="GROND">{% trans "Grond" %}</option>
              <option value="ANDERE">{% trans "Andere" %}</option>
        </div>
        <div class="col-md-6"/>
          <p>
            <label class="searchlabel" for="id_pricelgte">{% trans "Prijs omvang" %}:</label>
            <input type="text" name="range_value" id="amount" readonly style="border:0; color:#0d3532; font-weight:bold;">
          </p>
          <div id="slider-range"></div><p class="break"></p>
        </div>
      </tr>
    </table>
    <div class="col-md-12"/>
      <button type="submit" class="btn-searchfilter">{% trans "Zoeken" %}</button>
    </div>
  </form>
</div>
</div>
<p class="break">

<div class="container">
{% if string %}
  <p> {% trans "Geen zoekcriteria ontvangen" %}</p>
{% endif %}
<div class="aanbod">
  {% if kopen_list %}
    <!--Oplijsting van huizen die voldoen aan zoekcriteria-->
    <h1>{% trans "Huizen te koop" %} :</h1>
      {% for estate in kopen_list %}
        <div class="col-md-6" style="border-color:black;">
          <ul class="IDK" id="menu">
            <li>
              <article>
                <a href="/pand/{{ estate.id }}">
                  <div class="polaroid">
                    <div class="kijkerImg" style="background-image:url('../../media/{{estate.get_estateDisplayImage.0.image}}');">
                      <div class="container kijkerGegevens">
                          <h1>{{ estate.town }}</h1>
                          <h2>{{ estate.adres }} {{ estate.house_number }} </h2>
                      </div>

                      <div class="container kijkerPrijs">
                          <p> {% if estate.sale and estate.rent %}
                                <h2 class="price">
                                  <p>{% trans "Koopprijs" %}: €{{ estate.sale_price|intcomma }}</p>
                                  <p>{% trans "Huurprijs" %}: €{{ estate.rent_price|intcomma}}</p>
                                </h2>
                              {% elif estate.sale %}
                                  <h2 class="price">{% trans "Koopprijs" %}: €{{ estate.sale_price|intcomma}} </h2>
                                {% elif estate.rent %}
                                  <h2 class="price">{% trans "Huurprijs" %}: €{{ estate.rent_price|intcomma}} </h2>
                                {% endif %}
                            </p>
                      </div>

                      <div class="container kijkerLijn"></div>

                      <div class="container kijkerOppervlakte">
                        <img class="kijkerLogo ruler" src="{% static "img/ruler.png" %}"/>
                        <h2 class="surface"> {{estate.surface}} m²</h2>
                      </div>

                      <div class="container kijkerDetails">
                        <p class="bRoom">{{ estate.bedrooms }}</p>
                        <p class="bRoom">{{ estate.bathrooms}}</p>
                        <img class="kijkerLogo bedrooms" src="{% static "img/bedrooms.png" %}"/>
                        <img class="kijkerLogo bathrooms" src="{% static "img/bathroom.png" %}"/>
                      </div>
                    </div>
                  </div>
                </a>
              </article>
            </li>
          </ul>
        </div>
      {% endfor %}

  {% else %}
    <h2>{% trans "Geen huizen beschikbaar" %}</h2>
  {% endif %}
</div>
</div>
<div class="container" style="box-shadow:none;background-color:rgba(0,0,0,0);">
  <div class="pagination">
    <span class="step-links">
        {% if kopen_list.has_previous %}
            <a href="?page={{ kopen_list.previous_page_number }}">{% trans "Vorige" %}</a>
        {% endif %}

        <span class="current">
          {% blocktrans with t_num=huren_list.number t_pag_num=huren_list.paginator.num_pages %}
            Pagina {{ t_num }} van {{ t_pag_num }}
          {% endblocktrans %}
        </span>

        {% if kopen_list.has_next %}
            <a href="?page={{ kopen_list.next_page_number }}">{% trans "Volgende" %}</a>
        {% endif %}
    </span>
  </div>
</div>
<script type="text/javascript" src="../../static/js/class-helper.js"></script>
<script type="text/javascript" src="../../static/js/LazyImage.js"></script>
<script type="text/javascript" src="../../static/js/tap.js"></script>
<script type="text/javascript" src="../../static/js/priceRange.js" ></script>
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script>
function goBack() {
    window.history.back();
}
</script>
{% endblock %}

websiteSofie/templates/websiteSofie/unsubscribe.html
{% extends 'websiteSofie/base.html' %}

{% load staticfiles %}

{% block content %}

<div class="container">
  <form action="/unsubscribe/" method="GET">
    {% csrf_token %}
    <table align="center">
      <tr><th><label for="id_email">Email:</label></th><td>
      <input id="id_email" maxlength="50" name="email" type="email" /></td></tr>
    </table>
    <input type="submit" value="Submit" />
  </form>
</div>

{% endblock %}